name: gobot-blink-bnr34gt40-v2
version: master
summary:  Blink snap for the Raspberry Pi with Gobot
description: |
  This is a simple example to blink an LED in the Raspberry Pi
  using the Gobot framework.

base: core18
confinement: devmode

architectures:
  - build-on: i386
    run-on: armhf

apps:
  gobot-blink-bnr34gt40-v2:
    command: gobot-blink

parts:
  gobot-blink:
    source: .
    plugin: go
    go-importpath: github.com/bnr34gt40/gobot-blink
    build-packages: [git, gcc]
